repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2   # версия Ruff
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.24.0
    hooks:
      - id: django-upgrade
        args: ["--target-version", "4.2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: debug-statements
